### PR TITLE
Fix the parameters included in the names of functions and datatypes in SMTLIB code

### LINKED ISSUE #79: Don't include boolean constant values in Game State names
We need to include integer constant names in the name, because the Bits types might be diffferent. However, right now we also include boolean values. This means we can't compare the states of two game instances that only differ in the value of a boolen constant parameter. While this is not wrong, it's a restriction that is not necessary.

### PR DESCRIPTION
**Pull request by keks**
Closes #79

### CODE REVIEW

**Comment by keks** [comment]
When reviewing, maybe start with src/writers/smt/patterns/instance_names.rs because that defines all the new types and traits.

File: src/writers/smt/patterns/datastructures/normal_return.rs [hunk 1]
```diff
@@ -33,53 +34,52 @@ impl<'a> DatastructurePattern<'a> for ReturnPattern<'a> {
...
-            pkg_params,
-        } = self;
-
-        let game_encoded_params = encode_params(only_non_function_expression(*game_params));
-        let pkg_encoded_params = encode_params(only_non_function_expression(*pkg_params));
-        format!("<{camel_case}-{game_name}-{game_encoded_params}-{pkg_name}-{pkg_encoded_params}-{oracle_name}>")
+        let game_encoded_params = encode_params(only_ints(self.game_params));
+        let pkg_encoded_params = encode_params(only_ints(self.pkg_params));
+
+        SortNameBuilder::new()
```
Comment (siccegge) [inline src/writers/smt/patterns/datastructures/normal_return.rs:40]: that also changes the output, though seems intentional/correct?

Comment (keks) [reply src/writers/smt/patterns/datastructures/normal_return.rs:40]: Do you mean because the params are only added optionally? Yes, that is intentional.

Comment (siccegge) [reply src/writers/smt/patterns/datastructures/normal_return.rs:40]: its using a SortName now and used FunctionName syntax before (which arguably was wrong)
