### PR TITLE
Fix/103 108 encode consts in types to proof level

### LINKED ISSUE #103: Parameters encoded in names should always be resolved up to the proof level
When addressing #79 in #99 we found that when including parameters in names, we sometimes don't use the proof-level name but some intermediate one. This is most likely wrong.

### LINKED ISSUE #108: Bits(n) does not get along with randomness mapping
When building the `rand-is-eq` function, we look at the intersection between left and right types.
This is done somewhat simplistically and even if both left and right game inherit the same `n` from the proof their sampling types are different:

```
Bits(Identifier(PackageIdentifier(Const(PackageConstIdentifier { pkg_name: "Rand", name: "n", tipe: Integer, game_assignment: Some(Identifier(GameIdentifier(Const(GameConstIdentifier { game_name: "SmallComposition", name: "n", tipe: Integer, game_inst_name: None, proof_name: None, inst_info: None, assigned_value: None })))), pkg_inst_name: Some("rand"), game_name: Some("SmallComposition"), game_inst_name: None, proof_name: None }))))
```

vs

```
Bits(Identifier(PackageIdentifier(Const(PackageConstIdentifier { pkg_name: "Rand", name: "n", tipe: Integer, game_assignment: Some(Identifier(GameIdentifier(Const(GameConstIdentifier { game_name: "MediumComposition", name: "n", tipe: Integer, game_inst_name: None, proof_name: None, inst_info: None, assigned_value: None })))), pkg_inst_name: Some("rand"), game_name: Some("MediumComposition"), game_inst_name: None, proof_name: None }))))
```

Which results in an empty `rand-is-eq`

```
(define-fun rand-is-eq ((sample-id-left Int)
 (sample-id-right Int)
 (sample-ctr-left Int)
 (sample-ctr-right Int)
)
 Bool true)
```

### PR DESCRIPTION
**Pull request by keks**
This is still very unfinished, but it addresses two related issues:

- #103 
- #108 

so far I've only started looking at #108.

Closes #103
Closes #108

### CODE REVIEW

File: src/gamehops/equivalence/mod.rs [hunk 1]
```diff
@@ -1631,29 +1632,65 @@ impl<'a> EquivalenceContext<'a> {
...
+        let right_types: HashSet<Type> = HashSet::from_iter(
+            self.sample_info_right()
+                .tipes
+                .iter()
+                .cloned()
+                .map(type_use_proof_ident),
+        );
+
+        println!("randeq: types found in left:  {left_types:?}");
+        println!("randeq: types found in right: {right_types:?}");
```
Comment (keks) [inline src/gamehops/equivalence/mod.rs:1671]: rm

File: src/gamehops/equivalence/mod.rs [hunk 2]
```diff
@@ -1631,29 +1632,65 @@ impl<'a> EquivalenceContext<'a> {
...
 
         let types: Vec<&Type> = left_types.intersection(&right_types).collect();
 
+        println!("randeq: intersection: {types:?}");
+
```
Comment (keks) [inline src/gamehops/equivalence/mod.rs:1676]: rm

File: src/transforms/type_extract.rs [hunk 3]
```diff
@@ -26,40 +31,52 @@ impl super::Transformation for Transformation<'_> {
     }
 }
 
+fn record_type(set: &mut HashSet<Type>, ty: Type) {
+    if let Type::Bits(cs) = &ty {
+        if let CountSpec::Identifier(ident) = cs.as_ref() {
+            println!(
+                "type extract: found Bits ident {:?}",
+                ident.as_proof_identifier()
+            )
```
Comment (keks) [inline src/transforms/type_extract.rs:40]: rm

File: src/transforms/type_extract.rs [hunk 4]
```diff
@@ -14,8 +14,13 @@ impl super::Transformation for Transformation<'_> {
     fn transform(&self) -> Result<(Composition, HashSet<Type>), Infallible> {
         let mut set = HashSet::new();
 
+        // TODO: extract types of game state, params, oracle args, oracle return
+
         let insts = &self.0.pkgs.iter();
         let oracles = insts.clone().flat_map(|inst| inst.pkg.oracles.clone());
+
+        // TODO: extract types of package state, params, oracle args, oracle return
+
```
Comment (keks) [inline src/transforms/type_extract.rs:23]: are these todos still relevant?
