### PR TITLE
messy fix for the identifier resolution problem

### LINKED ISSUE #61: SMT-LIB code generation is broken due to identifiers not being resolved in CountSpecs

### PR DESCRIPTION
**Pull request by keks**
This PR is for fixing resolution and comparison of identifiers inside count specs.

Fixes #61

### CODE REVIEW

File: src/types.rs [hunk 1]
```diff
@@ -26,11 +26,21 @@ impl Type {
             replace.clone()
         } else {
             match self {
+                Type::Bits(count_spec) if matches!(count_spec.as_ref(), CountSpec::Identifier(Identifier::PackageIdentifier(PackageIdentifier::Const(pkg_const_ident ))) if &pkg_const_ident.name == "n" && pkg_const_ident.tipe == Type::Integer) => {
+                    if rules.is_empty() {
+                        print!(".");
+                        panic!();
```
Comment (siccegge) [inline src/types.rs:32]: interesting error handling

File: src/packageinstance.rs [hunk 2]
```diff
@@ -234,13 +234,142 @@ pub(crate) mod instantiate {
...
+                    )))
+                }
+                (_, other @ (CountSpec::Any | CountSpec::Literal(_))) => other,
+
+                // not entirely sure about this one:
+                (_, other) => other,
+            }
+        }
+
+        pub(crate) fn base_rewrite_rules(&self) -> Vec<(Type, Type)> {
```
Comment (siccegge) [inline src/packageinstance.rs:309]: Could use some comment saying what this is supposed to do exactly
